# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDFtoCSV(object):
    def setupUi(self, PDFtoCSV):
        PDFtoCSV.setObjectName("PDFtoCSV")
        PDFtoCSV.resize(530, 189)
        self.centralwidget = QtWidgets.QWidget(PDFtoCSV)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 491, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 70, 491, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 531, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 100, 171, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        PDFtoCSV.setCentralWidget(self.centralwidget)

        self.retranslateUi(PDFtoCSV)
        QtCore.QMetaObject.connectSlotsByName(PDFtoCSV)

    def retranslateUi(self, PDFtoCSV):
        _translate = QtCore.QCoreApplication.translate
        PDFtoCSV.setWindowTitle(_translate("PDFtoCSV", "PDF to CSV "))
        self.label.setText(_translate("PDFtoCSV", "Path del directorio:"))
        self.pushButton.setText(_translate("PDFtoCSV", "Comenzar"))
        self.label_3.setText(_translate("PDFtoCSV", "© Eliaz Bobadilla 2021"))
        self.label_4.setText(_translate("PDFtoCSV", " Archivos Procesados"))

